asset: "stride.zip"
tap: "phogolabs/homebrew-tap/stride.rb"
template: |
  class Stride < Formula
    desc "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version "$STABLE_VERSION"
    url "$STABLE_URL"
    sha256 "$STABLE_SHA256"

    def install
      prefix.install "stride"
    end
  end
