asset: "stride-$VERSION_NUMBER.zip"
tap: "phogolabs/homebrew-tap/stride.rb"
template: |
  class Stride < Formula
    desc "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    version "$STABLE_VERSION"
    url "$STABLE_URL"
    sha256 "$STABLE_SHA256"

    def install
      mv "stride_darwin_amd64", "stride"
      bin.install "stride"
    end

    test do
      assert_match "stride version #{version}", shell_output("#{bin}/stride -v2>&1")
    end
  end
