name: pipeline
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pipeline:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Run Tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload tests coverage to codeconv.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.github.ref == 'refs/heads/master'
