name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  pipeline:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install Golang tools
        run: GO111MODULE=on go install github.com/mitchellh/gox
      - name: Build project
        run: ls -l $GOPATH && ls -l $GOBIN
