name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      -
        name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
