name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install Golang tools
        run: go install github.com/mitchellh/gox
      - name: Build project
        run: gox github.com/phogolabs/stride/cmd/stride
