name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Version
        id: get_version
        run: echo ::set-output name=NUMBER::${GITHUB_REF/refs\/tags\//}
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install Golang tools
        run: go install github.com/mitchellh/gox
      - name: Build Project
        run: $GOPATH/bin/gox -ldflags "-X main.Version=${{ steps.get_version.NUMBER }}" github.com/phogolabs/stride/cmd/stride
        working-directory: ./build
